version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: rentalx
    links:
      - database_ignite
    depends_on:
      - database_ignite
    ports: 
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/bcrypt/
    environment:
      DATABASE_URL: postgres://docker:ignite@database_ignite:5432/rentalx

volumes:
  pgdata:
    driver: local
# docker-compose up --force-recreate -d
# docker logs rentalx -f
